[package]
name = "radix-engine-tests"
version = "0.9.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine = { path = "../radix-engine", default-features = false }
radix-engine-constants = { path = "../radix-engine-constants" }
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
transaction = { path = "../transaction", default-features = false }
utils = { path = "../utils", default-features = false }

[dev-dependencies]
wabt = { version = "0.10.0" }
criterion = { version = "0.3", features = ["html_reports"] }
scrypto = { path = "../scrypto", default-features = false }
scrypto-unit = { path = "../scrypto-unit", default-features = false }
rand = { version = "0.8.5" }
rand_chacha = { version = "0.3.1" }
rayon = "1.5.3"
serde = { version = "1.0.144", default-features = false }
serde_json = { version = "1.0.81", default-features = false }
crossbeam = { version = "0.8.2" }

[[bench]]
name = "radix_engine"
harness = false

[[bench]]
name = "transaction"
harness = false

[[bench]]
name = "wasm"
harness = false

[[bench]]
name = "radiswap"
harness = false

[[bench]]
name = "resources_usage"
harness = false
required-features = ["cpu_ram_metrics"]

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "transaction/std", "radix-engine/std", "radix-engine-interface/std", "utils/std", "scrypto/std", "scrypto-unit/std"]
alloc = ["sbor/alloc", "transaction/alloc", "radix-engine/alloc", "radix-engine-interface/alloc", "utils/alloc", "scrypto/alloc", "scrypto-unit/alloc"]
wasmer = ["radix-engine/wasmer"]
cpu_ram_metrics = ["radix-engine/cpu_ram_metrics"]
flamegraph = []