[package]
name = "transaction-data"
version = "0.9.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
transaction-derive = { path = "../transaction-derive", default-features = false }
utils = { path = "../utils", default-features = false }

hex = { version = "0.4.3", default-features = false }
serde = { version = "1.0.144", default-features = false, optional = true }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "hex/std", "utils/std", "transaction-derive/std"]
alloc = ["sbor/alloc", "hex/alloc", "utils/alloc", "transaction-derive/alloc"]
serde = ["serde/derive"]