[workspace]
members = [
    "sbor-derive",
    "sbor",
    "sbor-tests",
    "scrypto-abi",
    "scrypto-derive",
    "scrypto",
    "scrypto-tests",
    "scrypto-unit",
    "transaction",
    "radix-engine",
    "radix-engine-stores",
    "simulator",
]

# Note - we don't include any Scrypto packages here - they should be loaded/built separately, as they need separate profiles.
# They include a [workspace] in each of their Cargo.tomls to avoid falling back to the root workspace
