[package]
name = "radix-engine"
version = "0.5.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
scrypto = { path = "../scrypto", default-features = false }
wasmi = { git = "https://github.com/radixdlt/wasmi", branch = "expose-exports" }
colored = { version = "2.0.0", default-features = false }
lru = { version = "0.7.5" }
bencher = { version = "0.1.5" }
hex = { version = "0.4.3", default-features = false }
indexmap = { version = "1.8.1" }

[dev-dependencies]
wabt = { version = "0.10.0" }

[[bench]]
name = "bench"
harness = false

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "scrypto/std", "wasmi/std"]
alloc = ["sbor/alloc", "scrypto/alloc"]
