[package]
name = "radix-engine-interface"
version = "0.9.0"
edition = "2021"

[dependencies]
sbor = { path = "../sbor", default-features = false }
radix-engine-derive = { path = "../radix-engine-derive", default-features = false }
radix-engine-common = { path = "../radix-engine-common", default-features = false }
scrypto-abi = { path = "../scrypto-abi", default-features = false }
utils = { path = "../utils", default-features = false }

hex = { version = "0.4.3", default-features = false }
strum = { version = "0.24", default-features = false, features = ["derive"] }
bitflags = { version = "1.3" }

[dev-dependencies]
serde_json = { version = "1.0.81", default-features = false }
criterion = { version = "0.3", features = ["html_reports"] }
# This is for math benchmarks for comparison purposes.
# Fast alternative to bigint but unfortunately not cross-compiled to WASM
rug = { version = "1.18" }
num-integer = { version = "0.1.45", default-features = false }
ethnum = {version = "1.3.2", default-features = false }

[[bench]]
name = "math"
harness = false

[[bench]]
name = "schema"
harness = false

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["hex/std", "sbor/std", "scrypto-abi/std", "radix-engine-derive/std", "radix-engine-common/std", "strum/std", "utils/std", "serde_json/std"]
alloc = ["hex/alloc", "sbor/alloc", "scrypto-abi/alloc", "radix-engine-derive/alloc", "radix-engine-common/alloc", "utils/alloc", "serde_json/alloc"]

# Turn on this feature to enable tracing.
trace = ["radix-engine-derive/trace"]

# Enable serde derives
serde = ["utils/serde", "sbor/serde", "hex/serde", "scrypto-abi/serde"]

