[package]
name = "metadata"
version = "0.13.0"
edition = "2021"

[dependencies]
sbor = { path = "../../../sbor" }
scrypto = { path = "../../../scrypto" }

[dev-dependencies]
transaction = { path = "../../../transaction" }
radix-engine = { path = "../../../radix-engine" }
scrypto-unit = { path = "../../../scrypto-unit" }
native-sdk = { path = "../../../native-sdk" }

[lib]
crate-type = ["cdylib", "lib"]
