[package]
name = "sbor"
version = "0.8.0"
edition = "2021"

[dependencies]
sbor-derive = { path = "../sbor-derive" }
hashbrown = { version = "0.12.1", optional = true }
serde = { version = "1.0.137", default-features = false, optional = true, features=["derive"] }
indexmap = { version = "1.9.2", default-features = false, optional = true }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["serde?/std"]
alloc = ["hashbrown", "serde?/alloc"]

# Enable serde derives for SBOR value and type models
serde = ["dep:serde"]

# Enable tracing
trace = ["sbor-derive/trace"]
