[package]
name = "radix-engine-stores"
version = "0.7.0"
edition = "2021"

[dependencies]
radix-engine = { path = "../radix-engine" }
radix-engine-interface = { path = "../radix-engine-interface", default-features = false }
sbor = { path = "../sbor" }
rocksdb = { version = "0.19.0", optional = true }

[features]
rocksdb = ["dep:rocksdb"]