name: Benchmark PR

on:
  pull_request:
    # Run on PR against any branch

concurrency:
  group: benchmark-comparison-${{ github.ref }}
  cancel-in-progress: true

jobs:
  benchmark:
    name: Run bench
    runs-on: gh-runner-scrypto-ubuntu-jammy-16-cores
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - uses: radixdlt/criterion-compare-action@update-same-commit
        with:
          branchName: ${{ github.base_ref }}
