name: scrypto builder publish

on:
  workflow_dispatch:
    inputs:
      image-label:
        description: "Docker image label to be published"
  push:
    branches:
      - chore/publish-simulator-image

jobs:

  oidc_debugger:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    name: A test of the oidc debugger
    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'https://github.com/github'

  build-amd:
    needs: oidc_debugger
    uses: radixdlt/public-iac-resuable-artifacts/.github/workflows/docker-build.yml@main
    with:
      runs_on: ubuntu-latest-16-cores 
      image_registry: "docker.io"
      image_organization: "radixdlt"
      image_name: "scrypto-builder"
      tag: latest
      context: "."
      dockerfile: "Dockerfile"
      platforms: "linux/amd64"
      provenance: "false"
      scan_image: true
      snyk_target_ref: ${{ github.ref_name }}
      enable_dockerhub: true
      post_script: "./update-assets.sh --reuse-image --image-tag latest"
    secrets:
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDP }}
      service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      role_to_assume: ${{ secrets.DOCKERHUB_RELEASER_ROLE }}

